name: CI(OTAPI3)

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        # If there are no submodules to checkout, this remains unchanged

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.100"

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["win-x64", "osx-x64", "linux-x64", "linux-arm64", "linux-arm"]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.100"

      - name: Restore dependencies
        run: dotnet restore

      - name: Install msgfmt
        run: sudo apt-get install -y gettext

      - name: Produce build
        run: |
          cd EthnessaLauncher
          dotnet publish -r ${{ matrix.arch }} -f net6.0 -c Release -p:PublishSingleFile=true --self-contained false

      - name: Chmod scripts
        if: ${{ matrix.arch != 'win-x64' }}
        run: |
          chmod +x EthnessaLauncher/bin/Release/net6.0/${{ matrix.arch }}/publish/Ethnessa

      # Additional steps for packaging and uploading artifacts remain unchanged
      # preserve file perms: https://github.com/actions/upload-artifact#maintaining-file-permissions-and-case-sensitive-files
      - name: Tarball artifact (non-Windows)
        if: ${{ matrix.arch != 'win-x64' }}
        run: |
          cd EthnessaLauncher/bin/Release/net6.0/${{ matrix.arch }}/publish/
          tar -cvf ../../../../../../Ethnessa-${{ matrix.arch }}-Release.tar *

      - name: Upload artifact (non-Windows)
        uses: actions/upload-artifact@v3
        if: ${{ matrix.arch != 'win-x64' }}
        with:
          name: Ethnessa-${{ matrix.arch }}-Release
          path: Ethnessa-${{ matrix.arch }}-Release.tar

      - name: Upload artifact (Windows)
        uses: actions/upload-artifact@v3
        if: ${{ matrix.arch == 'win-x64' }}
        with:
          name: Ethnessa-${{ matrix.arch }}-Release
          path: EthnessaLauncher/bin/Release/net6.0/${{ matrix.arch }}/publish/
